<?php

/**
 * Implements hook_ctools_plugin_directory()
 */
function panels_bootstrap_styles_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('styles'))) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_theme()
 */
function panels_bootstrap_styles_theme() {
  $theme = array();

  $theme['panels_bootstrap_pane'] = array(
    'variables' => array(
      'output' => array(),
      'pane' => array(),
      'display' => array()
    ),
    'path' => drupal_get_path('module', 'panels_bootstrap_styles') . '/templates',
    'template' => 'panels-bootstrap-pane',
  );

  return $theme;
}

/**
 * Retrieves a single or all substyles.
 * @param string $name
 * @return array
 */
function panels_bootstrap_styles_load_substyles($name = NULL) {
  $substyles = &drupal_static(__FUNCTION__, array());

  if (empty($substyles)) {
    $substyles = module_invoke_all('panels_bootstrap_substyles');
    $default = array(
      'description' => '',
    );
    foreach ($substyles as $id => &$substyle) {
      $substyle = $default + $substyle;
      $substyle['title'] = !empty($substyle['title']) ? $substyle['title'] : $id;
      $substyle['name'] = !empty($substyle['name']) ? $substyle['name'] : $id;
    }
  }

  if ($name) {
    return $substyles[$name];
  }
  return $substyles;
}

/**
 * Implements hook_panels_bootstrap_substyles.
 */
function panels_bootstrap_styles_panels_bootstrap_substyles() {

  $styles = array(
    'panel' => array(
      'name' => 'panel',
      'title' => 'Panel',
      'description' => 'Renders as bootstrap panel class.',
      'panes' => TRUE,
      'regions' => TRUE,
      'collapsible' => TRUE,
      'modifier_classes' => array(
        'panel-primary' => 'Primary',
        'panel-success' => 'Success',
        'panel-info' => 'Info',
        'panel-warning' => 'Warning',
        'panel-danger' => 'Danger',
      ),
      'hide_classes' => TRUE,
      'additional_classes' => TRUE,
    ),
    'jumbotron' => array(
      'name' => 'jumbotron',
      'title' => 'Jumbotron',
      'description' => 'Renders as bootstrap jumbotron class.',
      'panes' => TRUE,
      'regions' => TRUE,
      'collapsible' => FALSE,
      'modifiers' => FALSE,
      'hide_options' => TRUE,
      'additional_classes' => TRUE,
    ),
  );
  return $styles;
}

/**
 * Implements hook_preprocess_panels_pane_bootstrap().
 */
function template_preprocess_panels_bootstrap_pane(&$vars, $hook) {
  $id_index = &drupal_static(__FUNCTION__, 0);

  $content = &$vars['content'];

  $vars['contextual_links'] = array();
  $vars['classes_array'] = array();
  $vars['admin_links'] = '';

  if (module_exists('contextual') && user_access('access contextual links')) {
    $links = array();
    // These are specified by the content.
    if (!empty($content->admin_links)) {
      $links += $content->admin_links;
    }

    // Take any that may have been in the render array we were given and
    // move them up so they appear outside the pane properly.
    if (is_array($content->content) && isset($content->content['#contextual_links'])) {
      $element = array(
        '#type' => 'contextual_links',
        '#contextual_links' => $content->content['#contextual_links'],
      );
      unset($content->content['#contextual_links']);

      // Add content to $element array.
      if (is_array($content->content)) {
        $element['#element'] = $content->content;
      }

      $element = contextual_pre_render_links($element);
      $links += $element['#links'];
    }

    if ($links) {
      $build = array(
        '#prefix' => '<div class="contextual-links-wrapper">',
        '#suffix' => '</div>',
        '#theme' => 'links__contextual',
        '#links' => $links,
        '#attributes' => array('class' => array('contextual-links')),
        '#attached' => array(
          'library' => array(array('contextual', 'contextual-links')),
        ),
      );
      $vars['classes_array'][] = 'contextual-links-region';
      $vars['admin_links'] = drupal_render($build);
    }
  }
  // Basic classes.
  $vars['classes_array'][] = 'panel-pane-bootstrap';
  $vars['classes_array'][] = $vars['style_classes']['base_class'];
  $vars['classes_array'][] = $vars['style_classes']['modifier_class'];
  $vars['style_classes']['title_class'];
  $vars['id'] = '';

  // Add some usable classes based on type/subtype
  ctools_include('cleanstring');
  $type_class = $content->type ? 'pane-'. ctools_cleanstring($content->type, array('lower case' => TRUE)) : '';
  $subtype_class = $content->subtype ? 'pane-'. ctools_cleanstring($content->subtype, array('lower case' => TRUE)) : '';

  // Sometimes type and subtype are the same. Avoid redundant classes.
  $vars['classes_array'][] = $type_class;
  if ($type_class != $subtype_class) {
    $vars['classes_array'][] = $subtype_class;
  }

  // Add id and custom class if sent in.
  if (!empty($content->content)) {
    if (!empty($content->css_id)) {
      $vars['id'] = $content->css_id;
    }
    if (!empty($content->css_class)) {
      $vars['classes_array'][] = $content->css_class;
    }
  }

  // Set up some placeholders for constructing template file names.
  $delimiter = '__';

  // Add template file suggestion for content type and sub-type.
  $vars['theme_hook_suggestions'][] = $hook . $delimiter . $content->type;
  $vars['theme_hook_suggestions'][] = $hook . $delimiter . strtr($content->type, '-', '_') . $delimiter . strtr($content->subtype, '-', '_');

  $vars['pane_prefix'] = !empty($content->pane_prefix) ? $content->pane_prefix : '';
  $vars['pane_suffix'] = !empty($content->pane_suffix) ? $content->pane_suffix : '';

  $vars['title'] = !empty($content->title) ? $content->title : '';
  $vars['title_attributes_array']['class'][] = $vars['style_classes']['title_class'];

  $vars['feeds'] = !empty($content->feeds) ? implode(' ', $content->feeds) : '';

  $vars['links'] = !empty($content->links) ? theme('links', array('links' => $content->links)) : '';

  $vars['more'] = '';
  if (!empty($content->more)) {
    if (empty($content->more['title'])) {
      $content->more['title'] = t('more');
    }
    $vars['more'] = l($content->more['title'], $content->more['href'], $content->more);
  }

  $vars['header_attributes_array']['class'][] = $vars['style_classes']['header_class'];

  $vars['content'] = !empty($content->content) ? $content->content : '';
  $vars['content_attributes_array']['class'] = $vars['style_classes']['content_class'];

  $vars['footer'] = !empty($content->footer) ? $content->footer : '';
  $vars['footer_attributes_array']['class'][] = $vars['style_classes']['footer_class'];

  $vars['collapsible'] = !empty($vars['#collapsible']);
  $vars['collapsed'] = !empty($vars['#collapsed']);

  // For Collapsing to work we need an id and a title to be set.
  if ($vars['collapsible']) {
    if (empty($vars['id'])) {
      ++$id_index;
      $vars['id'] = 'pane-' . (string) $id_index;
    }
    if (empty($vars['title'])) {
      // TODO Come up with a better solution.
      $vars['title'] = '<span class="center-block">&nbsp;&nbsp;&nbsp;</span>';
    }
  }

}


/**
 * Implements hook_process_panels_bootstrap_pane().
 */
function template_process_panels_bootstrap_pane(&$variables, $hook) {
  // Flatten out classes.
  $variables['classes'] = implode(' ', $variables['classes_array']);

  if (!empty($variables['classes'])) {
    $variables['attributes_array']['class'] = $variables['classes'];
  }
  if (!empty($vars['id'])) {
    $vars['attributes_array']['id'] = $vars['id'];
  }

  // Flatten out the various attributes, because this function can be called
  // very often, and often with empty attributes, optimize performance by only
  // calling drupal_attributes() if necessary.
  $variables['attributes'] = $variables['attributes_array'] ? drupal_attributes($variables['attributes_array']) : '';
  $variables['title_attributes'] = $variables['title_attributes_array'] ? drupal_attributes($variables['title_attributes_array']) : '';
  $variables['header_attributes'] = $variables['header_attributes_array'] ? drupal_attributes($variables['header_attributes_array']) : '';
  $variables['content_attributes'] = $variables['content_attributes_array'] ? drupal_attributes($variables['content_attributes_array']) : '';
  $variables['footer_attributes'] = $variables['footer_attributes_array'] ? drupal_attributes($variables['footer_attributes_array']) : '';
}


